version: '3.8'

services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/peer_to_peer
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password_12345

  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=peer_to_peer'
      - 'POSTGRES_PASSWORD=password_12345'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
