services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=peer_to_peer'
      - 'POSTGRES_PASSWORD=password_12345'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379'
