spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/peer_to_peer
    username: admin
    password: password_12345
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

application:
  info:
    api: "/api/v1/p2p"

token:
  signing:
    key: "6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b"
  time:
    life-time: 10800000

